trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2 
  displayName: ".NET Core"
  inputs:
    version: '8.0.x'
    packageType: sdk

- script: dotnet restore
  displayName: 'dotnet restore'
  
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build'

- task: DotNetCoreCLI@2
  displayName: "Publish LOViT.Tracker"
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-r linux-x64 --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: "Upload Artifacts"
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'tracker' 